### PR TITLE
Include bias in Lab 4 model visualisation

### PR DESCRIPTION
**Pull request by jonathanjouty**
From what I can tell it looks like it has been left out!

### CODE REVIEW

**Comment by jonathanjouty** [comment]
Actually that looks a bit wrong to include it in the `for` loop :/
Probably this instead?

```
for weight, centre in zip(weights, centres):
    ys += weight * basis_function(xs, centre, scale)
ys += bias
```

**Comment by matt-graham** [comment]
Good spot. The latter is the correct I think. If you commit an updated version I'll merge this in.

Thanks!
Matt

**Comment by jonathanjouty** [comment]
There you go, "squash and merge" should do it.

**Comment by matt-graham** [comment]
Cheers, merged.

**Pull request merged**
